# Generated by Django 5.0.1 on 2024-03-15 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_first_name_remove_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='account_picture',
            new_name='profile_picture',
        ),
    ]
