# Generated by Django 5.0.1 on 2024-03-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_account_picture_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='accountuser',
            name='profile_picture',
            field=models.ImageField(default='11.jpg', upload_to='account_pictures/'),
            preserve_default=False,
        ),
    ]
