# Generated by Django 5.0.1 on 2024-03-15 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('profile_picture', models.ImageField(upload_to='account_pictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='accountuser',
            name='profile_picture',
        ),
    ]
