# Generated by Django 5.0.1 on 2024-04-01 21:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_profilecollection_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountuser',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
