# Generated by Django 5.0.1 on 2024-03-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
    ]
