# Generated by Django 5.0.1 on 2024-02-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NailDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('Dark', 'Dark'), ('Light', 'Light'), ('Red', 'Red'), ('Pink', 'Pink'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('White', 'White'), ('Black', 'Black'), ('Gold', 'Gold'), ('Nude', 'Nude'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Green', 'Green'), ('Brown', 'Brown'), ('Gray', 'Gray')], default='Dark', max_length=20)),
                ('size', models.CharField(choices=[('Square', 'Square'), ('Round', 'Round'), ('Oval', 'Oval'), ('Almond', 'Almond'), ('Stiletto', 'Stiletto'), ('Coffin', 'Coffin')], default='Oval', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='nail_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modifited_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
