# Generated by Django 5.0.1 on 2024-02-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naildesign',
            name='description',
        ),
    ]
