# Generated by Django 5.0.1 on 2024-02-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_naildesign_colors_delete_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naildesign',
            name='colors',
            field=models.CharField(choices=[('DARK', 'DARK'), ('LIGHT', 'LIGHT'), ('RED', 'RED'), ('PINK', 'PINK'), ('BLUE', 'Blue'), ('PURPLE', 'Purple'), ('WHITE', 'White'), ('BLACK', 'Black'), ('GOLD', 'Gold'), ('NUDE', 'Nude'), ('YELLOW', 'Yellow'), ('ORANGE', 'Orange'), ('GREEN', 'Green'), ('BROWN', 'Brown'), ('GRAY', 'Gray')], max_length=20),
        ),
    ]
