# Generated by Django 5.0.1 on 2024-02-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_naildesign_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naildesign',
            name='size',
            field=models.CharField(choices=[('Square', 'Square'), ('Round', 'Round'), ('Oval', 'Oval'), ('Almond', 'Almond'), ('Stiletto', 'Stiletto'), ('Coffin', 'Coffin')], max_length=20),
        ),
    ]
