# Generated by Django 5.0.1 on 2024-04-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='nails_design',
            new_name='nails_designs',
        ),
    ]
